# Generated by Django 4.2.3 on 2023-12-12 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_laptop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('author_name', models.CharField(max_length=256)),
                ('status', models.CharField(choices=[('posted', 'Опубликован'), ('not_posted', 'Не опубликован'), ('banned', 'Забанен')], default='not_posted', max_length=256)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_posted', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('fun', 'Funny posts'), ('news', 'News posts'), ('other', 'Any other topics')], max_length=256)),
            ],
        ),
    ]
