# Generated by Django 4.2.3 on 2023-12-12 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0003_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text',
            field=models.CharField(default='', max_length=16384),
        ),
    ]
