# Generated by Django 4.2.3 on 2023-12-12 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0005_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('fun', 'Funny posts'), ('news', 'News posts'), ('other', 'Any other topics')], max_length=256, null=True),
        ),
    ]
